Updated to nullsafety with the latest and greatest (injectable, icapp…
icapps/flutter-icapps-generator pull request #21
Opened 2021-05-12 16:48 UTC by ikbendewilliam

Updated to nullsafety with the latest and greatest (injectable, icapos_architecture)

2021-05-17 12:58 UTC, vanlooverenkoen requested changes

2021-05-17 12:58 UTC, vanlooverenkoen commented on bin/icapps_generator.dart
> +const NO_INJECTABLE_ARG = '--no-di';
your idea of moving to --no-di is indeed more generic. But I think we should use an other constant name. NO_DI_ARG for example

2021-05-17 12:58 UTC, vanlooverenkoen commented on bin/icapps_generator.dart
> +  // await FileCreatorHelper.updateInjector(params.projectName, screenName);
is this comment still needed

2021-05-17 12:58 UTC, vanlooverenkoen commented on bin/src/file_creator_helper.dart
> +      ..writeln('  Future<void> init(${CaseUtil.getCamelcase(screenName)}Navigator navigator) async {')
format code

2021-05-17 12:58 UTC, vanlooverenkoen commented on example/.flutter-plugins
> +# This is a generated file; do not edit or check into version control.
do not check into version controll

2021-05-17 12:58 UTC, vanlooverenkoen commented on example/.flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"connectivity_plus","path":"/Users/williamverhaeghe/.pub-cache/hosted/pub.dartlang.org/connect
do not check into version controll

2021-05-17 12:58 UTC, vanlooverenkoen commented on example/lib/navigator/main_navigator.dart
>      assert(() {
assert can be replaced with simple if

2021-12-08 09:36 UTC, ikbendewilliam commented
Taken over and new PR created by colleague

2021-12-08 09:36 UTC, closed without merging